[pytest]
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:urllib3 .* doesn't match a supported version:requests.exceptions.RequestsDependencyWarning
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
